/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import dao.PanelSearch;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.Timer;
import javax.swing.border.Border;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.geom.RoundRectangle2D;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.border.EmptyBorder;
import javax.swing.border.TitledBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;

/**
 *
 * @author HP
 */
public class GD_Chinh extends javax.swing.JFrame {

    public Border default_border = BorderFactory.createMatteBorder(0, 0, 3, 0, new Color(153, 153, 153));
    public Border active_border = BorderFactory.createMatteBorder(0, 0, 3, 0, new Color(153, 204, 255));
    public JButton[] buttons;
    public Timer tm;
    public int x = 0;
    public String[] list = {
        "src\\imgVSicon\\clark-street-mercantile-P3pI6xzovu0-unsplash.jpg",
        "src\\imgVSicon\\clark-street-mercantile-ydcMwcfY5E0-unsplash.jpg",
        "src\\imgVSicon\\clark-street-mercantile-S042liZk3A8-unsplash1.jpg"

    };
    private JTableHeader heder;

    /**
     * Creates new form GD_Chinh
     */
    public GD_Chinh() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        Slider();
//        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 30, 30));
//        addBorder();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Main = new javax.swing.JPanel();
        pnl_Menu_main = new javax.swing.JPanel();
        pnl_Menu_logo = new javax.swing.JPanel();
        lbl_logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnl_Menu_button = new javax.swing.JPanel();
        pnl_button_TongQuan = new javax.swing.JPanel();
        lbl_logo_TongQuan = new javax.swing.JLabel();
        lbl_title_TongQuan = new javax.swing.JLabel();
        pnl_button_BanHang = new javax.swing.JPanel();
        lbl_logo_BanHang = new javax.swing.JLabel();
        lbl_title_BanHang = new javax.swing.JLabel();
        pnl_button_SanPham = new javax.swing.JPanel();
        lbl_logo_SanPham = new javax.swing.JLabel();
        lbl_title_SanPham = new javax.swing.JLabel();
        pnl_button_KhachHang = new javax.swing.JPanel();
        lbl_logo_KhachHang = new javax.swing.JLabel();
        lbl_title_KhachHang = new javax.swing.JLabel();
        pnl_button_NhanVien = new javax.swing.JPanel();
        lbl_logo_NhanVien = new javax.swing.JLabel();
        lbl_title_NhanVien = new javax.swing.JLabel();
        pnl_button_HoaDon = new javax.swing.JPanel();
        lbl_logo_HoaDon = new javax.swing.JLabel();
        lbl_title_HoaDon = new javax.swing.JLabel();
        pnl_button_HeThong = new javax.swing.JPanel();
        lbl_logo_HeThong = new javax.swing.JLabel();
        lbl_title_HeThong = new javax.swing.JLabel();
        pnl_button_ThongKe = new javax.swing.JPanel();
        lbl_logo_ThongKe = new javax.swing.JLabel();
        lbl_title_ThongKe = new javax.swing.JLabel();
        pnl_ThongTinTaiKhoan = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        lbl_icon_TaiKhoan = new javax.swing.JLabel();
        lbl_title_TaiKhoan = new javax.swing.JLabel();
        lbl_title_TaiKhoan1 = new javax.swing.JLabel();
        pnl_button_NhaCungCap = new javax.swing.JPanel();
        lbl_logo_NCC = new javax.swing.JLabel();
        lbl_title_NCC = new javax.swing.JLabel();
        btn_active_TTTK = new javax.swing.JButton();
        pnl_FormTongQuan = new javax.swing.JPanel();
        pnl_ImgTQ = new javax.swing.JPanel();
        lbl_ImgTQ = new javax.swing.JLabel();
        lbl_text = new javax.swing.JLabel();
        lbl_icon_TQ = new javax.swing.JLabel();
        pnl_profile1 = new javax.swing.JPanel();
        lbl_Img_profile1 = new javax.swing.JLabel();
        lbl_Name_profile1 = new javax.swing.JLabel();
        lbl_Title_profile1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnl_profile4 = new javax.swing.JPanel();
        lbl_Img_profile4 = new javax.swing.JLabel();
        lbl_Name_profile4 = new javax.swing.JLabel();
        lbl_Title_profile4 = new javax.swing.JLabel();
        pnl_profile5 = new javax.swing.JPanel();
        lbl_Img_profile5 = new javax.swing.JLabel();
        lbl_Name_profile5 = new javax.swing.JLabel();
        lbl_Title_profile5 = new javax.swing.JLabel();
        pnl_FormHoaDon = new javax.swing.JPanel();
        lbl_text_HoaDon = new javax.swing.JLabel();
        pnl_menuTab_HoaDon = new javax.swing.JPanel();
        btn_tab_dshd = new javax.swing.JButton();
        btn_tab_tkhd = new javax.swing.JButton();
        pnl_tab_Form_DSHoaDon = new javax.swing.JPanel();
        try {
            frmHoaDon1 = new Gui.FrmHoaDon();
        } catch (java.sql.SQLException e1) {
            e1.printStackTrace();
        }
        pnl_tab_FormTKHoaDon = new javax.swing.JPanel();
        frmSanPham2 = new Gui.FrmSanPham();
        frmKhachHang1 = new Gui.FrmKhachHang();
        frmBanHang1 = new Gui.FrmBanHang();
        frmNhanVien1 = new Gui.FrmNhanVien();
        frmNhaCungCap1 = new Gui.FrmNhaCungCap();
        frmHeThong1 = new Gui.FrmHeThong();
        frmThongKe1 = new Gui.FrmThongKe();
        frmThongTinTaiKhoan1 = new Gui.FrmThongTinTaiKhoan();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 700));

        pnl_Main.setBackground(new java.awt.Color(255, 255, 255));
        pnl_Main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_Menu_main.setBackground(new java.awt.Color(153, 204, 255));
        pnl_Menu_main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_Menu_logo.setBackground(new java.awt.Color(153, 204, 255));

        lbl_logo.setFont(new java.awt.Font("Berlin Sans FB Demi", 2, 85)); // NOI18N
        lbl_logo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_logo.setText("DAD ");

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Fashion");

        javax.swing.GroupLayout pnl_Menu_logoLayout = new javax.swing.GroupLayout(pnl_Menu_logo);
        pnl_Menu_logo.setLayout(pnl_Menu_logoLayout);
        pnl_Menu_logoLayout.setHorizontalGroup(
            pnl_Menu_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_logo, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_Menu_logoLayout.setVerticalGroup(
            pnl_Menu_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Menu_logoLayout.createSequentialGroup()
                .addComponent(lbl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pnl_Menu_main.add(pnl_Menu_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 130));

        pnl_Menu_button.setBackground(new java.awt.Color(153, 204, 255));
        pnl_Menu_button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_button_TongQuan.setBackground(new java.awt.Color(255, 255, 255));
        pnl_button_TongQuan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_button_TongQuanMouseClicked(evt);
            }
        });

        lbl_logo_TongQuan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_logo_TongQuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVSicon/house.png"))); // NOI18N

        lbl_title_TongQuan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_title_TongQuan.setForeground(new java.awt.Color(0, 0, 0));
        lbl_title_TongQuan.setText("Tổng Quản");

        javax.swing.GroupLayout pnl_button_TongQuanLayout = new javax.swing.GroupLayout(pnl_button_TongQuan);
        pnl_button_TongQuan.setLayout(pnl_button_TongQuanLayout);
        pnl_button_TongQuanLayout.setHorizontalGroup(
            pnl_button_TongQuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_button_TongQuanLayout.createSequentialGroup()
                .addComponent(lbl_logo_TongQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_title_TongQuan, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
        );
        pnl_button_TongQuanLayout.setVerticalGroup(
            pnl_button_TongQuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_logo_TongQuan, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(lbl_title_TongQuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnl_Menu_button.add(pnl_button_TongQuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 50));

        pnl_button_BanHang.setBackground(new java.awt.Color(153, 204, 255));
        pnl_button_BanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_button_BanHangMouseClicked(evt);
            }
        });

        lbl_logo_BanHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_logo_BanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVSicon/trade.png"))); // NOI18N

        lbl_title_BanHang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_title_BanHang.setForeground(new java.awt.Color(0, 0, 0));
        lbl_title_BanHang.setText("Bán Hàng");

        javax.swing.GroupLayout pnl_button_BanHangLayout = new javax.swing.GroupLayout(pnl_button_BanHang);
        pnl_button_BanHang.setLayout(pnl_button_BanHangLayout);
        pnl_button_BanHangLayout.setHorizontalGroup(
            pnl_button_BanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_button_BanHangLayout.createSequentialGroup()
                .addComponent(lbl_logo_BanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_title_BanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        pnl_button_BanHangLayout.setVerticalGroup(
            pnl_button_BanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_logo_BanHang, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(lbl_title_BanHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnl_Menu_button.add(pnl_button_BanHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 210, 50));

        pnl_button_SanPham.setBackground(new java.awt.Color(153, 204, 255));
        pnl_button_SanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_button_SanPhamMouseClicked(evt);
            }
        });

        lbl_logo_SanPham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_logo_SanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVSicon/checklist.png"))); // NOI18N

        lbl_title_SanPham.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_title_SanPham.setForeground(new java.awt.Color(0, 0, 0));
        lbl_title_SanPham.setText("Sản Phẩm");

        javax.swing.GroupLayout pnl_button_SanPhamLayout = new javax.swing.GroupLayout(pnl_button_SanPham);
        pnl_button_SanPham.setLayout(pnl_button_SanPhamLayout);
        pnl_button_SanPhamLayout.setHorizontalGroup(
            pnl_button_SanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_button_SanPhamLayout.createSequentialGroup()
                .addComponent(lbl_logo_SanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_title_SanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnl_button_SanPhamLayout.setVerticalGroup(
            pnl_button_SanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_logo_SanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(lbl_title_SanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnl_Menu_button.add(pnl_button_SanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 210, 50));

        pnl_button_KhachHang.setBackground(new java.awt.Color(153, 204, 255));
        pnl_button_KhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_button_KhachHangMouseClicked(evt);
            }
        });

        lbl_logo_KhachHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_logo_KhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVSicon/target.png"))); // NOI18N

        lbl_title_KhachHang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_title_KhachHang.setForeground(new java.awt.Color(0, 0, 0));
        lbl_title_KhachHang.setText("Khách Hàng");

        javax.swing.GroupLayout pnl_button_KhachHangLayout = new javax.swing.GroupLayout(pnl_button_KhachHang);
        pnl_button_KhachHang.setLayout(pnl_button_KhachHangLayout);
        pnl_button_KhachHangLayout.setHorizontalGroup(
            pnl_button_KhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_button_KhachHangLayout.createSequentialGroup()
                .addComponent(lbl_logo_KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_title_KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pnl_button_KhachHangLayout.setVerticalGroup(
            pnl_button_KhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_logo_KhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(lbl_title_KhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnl_Menu_button.add(pnl_button_KhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 210, 50));

        pnl_button_NhanVien.setBackground(new java.awt.Color(153, 204, 255));
        pnl_button_NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_button_NhanVienMouseClicked(evt);
            }
        });

        lbl_logo_NhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_logo_NhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVSicon/employee.png"))); // NOI18N

        lbl_title_NhanVien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_title_NhanVien.setForeground(new java.awt.Color(0, 0, 0));
        lbl_title_NhanVien.setText("Nhân Viên");

        javax.swing.GroupLayout pnl_button_NhanVienLayout = new javax.swing.GroupLayout(pnl_button_NhanVien);
        pnl_button_NhanVien.setLayout(pnl_button_NhanVienLayout);
        pnl_button_NhanVienLayout.setHorizontalGroup(
            pnl_button_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_button_NhanVienLayout.createSequentialGroup()
                .addComponent(lbl_logo_NhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_title_NhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        pnl_button_NhanVienLayout.setVerticalGroup(
            pnl_button_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_logo_NhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(lbl_title_NhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnl_Menu_button.add(pnl_button_NhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 210, 50));

        pnl_button_HoaDon.setBackground(new java.awt.Color(153, 204, 255));
        pnl_button_HoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_button_HoaDonMouseClicked(evt);
            }
        });

        lbl_logo_HoaDon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_logo_HoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVSicon/bill 1.png"))); // NOI18N

        lbl_title_HoaDon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_title_HoaDon.setForeground(new java.awt.Color(0, 0, 0));
        lbl_title_HoaDon.setText("Hóa Đơn");

        javax.swing.GroupLayout pnl_button_HoaDonLayout = new javax.swing.GroupLayout(pnl_button_HoaDon);
        pnl_button_HoaDon.setLayout(pnl_button_HoaDonLayout);
        pnl_button_HoaDonLayout.setHorizontalGroup(
            pnl_button_HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_button_HoaDonLayout.createSequentialGroup()
                .addComponent(lbl_logo_HoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_title_HoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        pnl_button_HoaDonLayout.setVerticalGroup(
            pnl_button_HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_logo_HoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(lbl_title_HoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnl_Menu_button.add(pnl_button_HoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 210, 50));

        pnl_button_HeThong.setBackground(new java.awt.Color(153, 204, 255));
        pnl_button_HeThong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_button_HeThongMouseClicked(evt);
            }
        });

        lbl_logo_HeThong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_logo_HeThong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVSicon/system.png"))); // NOI18N

        lbl_title_HeThong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_title_HeThong.setForeground(new java.awt.Color(0, 0, 0));
        lbl_title_HeThong.setText("Hệ Thống");

        javax.swing.GroupLayout pnl_button_HeThongLayout = new javax.swing.GroupLayout(pnl_button_HeThong);
        pnl_button_HeThong.setLayout(pnl_button_HeThongLayout);
        pnl_button_HeThongLayout.setHorizontalGroup(
            pnl_button_HeThongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_button_HeThongLayout.createSequentialGroup()
                .addComponent(lbl_logo_HeThong, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_title_HeThong, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_button_HeThongLayout.setVerticalGroup(
            pnl_button_HeThongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_logo_HeThong, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(lbl_title_HeThong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnl_Menu_button.add(pnl_button_HeThong, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 210, 50));

        pnl_button_ThongKe.setBackground(new java.awt.Color(153, 204, 255));
        pnl_button_ThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_button_ThongKeMouseClicked(evt);
            }
        });

        lbl_logo_ThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_logo_ThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVSicon/analytics.png"))); // NOI18N

        lbl_title_ThongKe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_title_ThongKe.setForeground(new java.awt.Color(0, 0, 0));
        lbl_title_ThongKe.setText("Thống Kê");

        javax.swing.GroupLayout pnl_button_ThongKeLayout = new javax.swing.GroupLayout(pnl_button_ThongKe);
        pnl_button_ThongKe.setLayout(pnl_button_ThongKeLayout);
        pnl_button_ThongKeLayout.setHorizontalGroup(
            pnl_button_ThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_button_ThongKeLayout.createSequentialGroup()
                .addComponent(lbl_logo_ThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_title_ThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_button_ThongKeLayout.setVerticalGroup(
            pnl_button_ThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_logo_ThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(lbl_title_ThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnl_Menu_button.add(pnl_button_ThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 210, 50));

        pnl_ThongTinTaiKhoan.setBackground(new java.awt.Color(153, 204, 255));
        pnl_ThongTinTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_ThongTinTaiKhoanMouseClicked(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVSicon/logout (1).png"))); // NOI18N
        jButton6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 0, 102), new java.awt.Color(255, 0, 51)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jButton6.setContentAreaFilled(false);

        lbl_icon_TaiKhoan.setBackground(new java.awt.Color(255, 255, 255));
        lbl_icon_TaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        lbl_icon_TaiKhoan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_icon_TaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVSicon/user.png"))); // NOI18N

        lbl_title_TaiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_title_TaiKhoan.setForeground(new java.awt.Color(0, 0, 0));
        lbl_title_TaiKhoan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title_TaiKhoan.setText("Tấn Đăng");

        lbl_title_TaiKhoan1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_title_TaiKhoan1.setForeground(new java.awt.Color(255, 0, 51));
        lbl_title_TaiKhoan1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title_TaiKhoan1.setText("ADMIN");

        javax.swing.GroupLayout pnl_ThongTinTaiKhoanLayout = new javax.swing.GroupLayout(pnl_ThongTinTaiKhoan);
        pnl_ThongTinTaiKhoan.setLayout(pnl_ThongTinTaiKhoanLayout);
        pnl_ThongTinTaiKhoanLayout.setHorizontalGroup(
            pnl_ThongTinTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ThongTinTaiKhoanLayout.createSequentialGroup()
                .addComponent(lbl_icon_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_ThongTinTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_title_TaiKhoan)
                    .addComponent(lbl_title_TaiKhoan1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl_ThongTinTaiKhoanLayout.setVerticalGroup(
            pnl_ThongTinTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ThongTinTaiKhoanLayout.createSequentialGroup()
                .addGroup(pnl_ThongTinTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_ThongTinTaiKhoanLayout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addComponent(lbl_title_TaiKhoan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_title_TaiKhoan1))
                    .addComponent(lbl_icon_TaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnl_Menu_button.add(pnl_ThongTinTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 200, 60));

        pnl_button_NhaCungCap.setBackground(new java.awt.Color(153, 204, 255));
        pnl_button_NhaCungCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_button_NhaCungCapMouseClicked(evt);
            }
        });

        lbl_logo_NCC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_logo_NCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVSicon/inventory.png"))); // NOI18N

        lbl_title_NCC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_title_NCC.setForeground(new java.awt.Color(0, 0, 0));
        lbl_title_NCC.setText("Nhà Cung Cấp");

        javax.swing.GroupLayout pnl_button_NhaCungCapLayout = new javax.swing.GroupLayout(pnl_button_NhaCungCap);
        pnl_button_NhaCungCap.setLayout(pnl_button_NhaCungCapLayout);
        pnl_button_NhaCungCapLayout.setHorizontalGroup(
            pnl_button_NhaCungCapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_button_NhaCungCapLayout.createSequentialGroup()
                .addComponent(lbl_logo_NCC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_title_NCC)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        pnl_button_NhaCungCapLayout.setVerticalGroup(
            pnl_button_NhaCungCapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_logo_NCC, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(lbl_title_NCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnl_Menu_button.add(pnl_button_NhaCungCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 210, 50));

        btn_active_TTTK.setContentAreaFilled(false);
        btn_active_TTTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_active_TTTKActionPerformed(evt);
            }
        });
        pnl_Menu_button.add(btn_active_TTTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 20, 50));

        pnl_Menu_main.add(pnl_Menu_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 210, 570));

        pnl_Main.add(pnl_Menu_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 700));

        pnl_FormTongQuan.setBackground(new java.awt.Color(255, 255, 255));
        pnl_FormTongQuan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_ImgTQ.setForeground(new java.awt.Color(255, 255, 255));

        lbl_text.setFont(new java.awt.Font("Constantia", 0, 120)); // NOI18N
        lbl_text.setForeground(new java.awt.Color(255, 255, 255));
        lbl_text.setText("Welcome");

        lbl_icon_TQ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVSicon/Component 1.png"))); // NOI18N

        javax.swing.GroupLayout pnl_ImgTQLayout = new javax.swing.GroupLayout(pnl_ImgTQ);
        pnl_ImgTQ.setLayout(pnl_ImgTQLayout);
        pnl_ImgTQLayout.setHorizontalGroup(
            pnl_ImgTQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ImgTQLayout.createSequentialGroup()
                .addComponent(lbl_ImgTQ, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnl_ImgTQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ImgTQLayout.createSequentialGroup()
                    .addContainerGap(297, Short.MAX_VALUE)
                    .addComponent(lbl_text)
                    .addContainerGap(298, Short.MAX_VALUE)))
            .addGroup(pnl_ImgTQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ImgTQLayout.createSequentialGroup()
                    .addContainerGap(399, Short.MAX_VALUE)
                    .addComponent(lbl_icon_TQ, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(419, Short.MAX_VALUE)))
        );
        pnl_ImgTQLayout.setVerticalGroup(
            pnl_ImgTQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_ImgTQ, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
            .addGroup(pnl_ImgTQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ImgTQLayout.createSequentialGroup()
                    .addContainerGap(49, Short.MAX_VALUE)
                    .addComponent(lbl_text)
                    .addContainerGap(163, Short.MAX_VALUE)))
            .addGroup(pnl_ImgTQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ImgTQLayout.createSequentialGroup()
                    .addContainerGap(208, Short.MAX_VALUE)
                    .addComponent(lbl_icon_TQ, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(41, Short.MAX_VALUE)))
        );

        pnl_FormTongQuan.add(pnl_ImgTQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 360));

        pnl_profile1.setBackground(new java.awt.Color(255, 255, 255));

        lbl_Img_profile1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVSicon/user1.jpg"))); // NOI18N

        lbl_Name_profile1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lbl_Name_profile1.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Name_profile1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Name_profile1.setText("Lê Tấn Đăng");

        lbl_Title_profile1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lbl_Title_profile1.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Title_profile1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Title_profile1.setText("19526881");

        javax.swing.GroupLayout pnl_profile1Layout = new javax.swing.GroupLayout(pnl_profile1);
        pnl_profile1.setLayout(pnl_profile1Layout);
        pnl_profile1Layout.setHorizontalGroup(
            pnl_profile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Name_profile1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
            .addComponent(lbl_Title_profile1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_profile1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_Img_profile1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_profile1Layout.setVerticalGroup(
            pnl_profile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_profile1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Img_profile1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Name_profile1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Title_profile1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_FormTongQuan.add(pnl_profile1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 150, 250));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("*Phát triển bởi:");
        pnl_FormTongQuan.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 100, 30));

        pnl_profile4.setBackground(new java.awt.Color(255, 255, 255));

        lbl_Img_profile4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVSicon/user1.jpg"))); // NOI18N

        lbl_Name_profile4.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lbl_Name_profile4.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Name_profile4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Name_profile4.setText("Lê Tấn Đăng");

        lbl_Title_profile4.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lbl_Title_profile4.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Title_profile4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Title_profile4.setText("19526881");

        javax.swing.GroupLayout pnl_profile4Layout = new javax.swing.GroupLayout(pnl_profile4);
        pnl_profile4.setLayout(pnl_profile4Layout);
        pnl_profile4Layout.setHorizontalGroup(
            pnl_profile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Name_profile4, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
            .addComponent(lbl_Title_profile4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_profile4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_Img_profile4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_profile4Layout.setVerticalGroup(
            pnl_profile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_profile4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Img_profile4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Name_profile4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Title_profile4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_FormTongQuan.add(pnl_profile4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 150, 250));

        pnl_profile5.setBackground(new java.awt.Color(255, 255, 255));

        lbl_Img_profile5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVSicon/user1.jpg"))); // NOI18N

        lbl_Name_profile5.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lbl_Name_profile5.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Name_profile5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Name_profile5.setText("Lê Tấn Đăng");

        lbl_Title_profile5.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lbl_Title_profile5.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Title_profile5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Title_profile5.setText("19526881");

        javax.swing.GroupLayout pnl_profile5Layout = new javax.swing.GroupLayout(pnl_profile5);
        pnl_profile5.setLayout(pnl_profile5Layout);
        pnl_profile5Layout.setHorizontalGroup(
            pnl_profile5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Name_profile5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_Title_profile5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_profile5Layout.createSequentialGroup()
                .addGap(0, 3, Short.MAX_VALUE)
                .addComponent(lbl_Img_profile5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_profile5Layout.setVerticalGroup(
            pnl_profile5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_profile5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Img_profile5, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Name_profile5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Title_profile5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pnl_FormTongQuan.add(pnl_profile5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 410, 150, 250));

        pnl_Main.add(pnl_FormTongQuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 1090, 700));

        pnl_FormHoaDon.setBackground(new java.awt.Color(255, 255, 255));
        pnl_FormHoaDon.setPreferredSize(new java.awt.Dimension(1090, 700));
        pnl_FormHoaDon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_text_HoaDon.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        lbl_text_HoaDon.setForeground(new java.awt.Color(0, 153, 204));
        lbl_text_HoaDon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_text_HoaDon.setText("Hóa Đơn");
        pnl_FormHoaDon.add(lbl_text_HoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 138, 30));

        pnl_menuTab_HoaDon.setBackground(new java.awt.Color(255, 255, 255));

        btn_tab_dshd.setBackground(new java.awt.Color(255, 255, 255));
        btn_tab_dshd.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_tab_dshd.setForeground(new java.awt.Color(0, 0, 0));
        btn_tab_dshd.setText("Danh Sách Hóa Đơn");
        btn_tab_dshd.setBorder(null);
        btn_tab_dshd.setContentAreaFilled(false);
        btn_tab_dshd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tab_dshdMouseClicked(evt);
            }
        });
        btn_tab_dshd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tab_dshdActionPerformed(evt);
            }
        });

        btn_tab_tkhd.setBackground(new java.awt.Color(255, 255, 255));
        btn_tab_tkhd.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_tab_tkhd.setForeground(new java.awt.Color(153, 153, 153));
        btn_tab_tkhd.setText("Tìm Kiếm Hóa Đơn");
        btn_tab_tkhd.setBorder(null);
        btn_tab_tkhd.setContentAreaFilled(false);
        btn_tab_tkhd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tab_tkhdMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_menuTab_HoaDonLayout = new javax.swing.GroupLayout(pnl_menuTab_HoaDon);
        pnl_menuTab_HoaDon.setLayout(pnl_menuTab_HoaDonLayout);
        pnl_menuTab_HoaDonLayout.setHorizontalGroup(
            pnl_menuTab_HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_menuTab_HoaDonLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(btn_tab_dshd)
                .addGap(44, 44, 44)
                .addComponent(btn_tab_tkhd)
                .addContainerGap(713, Short.MAX_VALUE))
        );
        pnl_menuTab_HoaDonLayout.setVerticalGroup(
            pnl_menuTab_HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_menuTab_HoaDonLayout.createSequentialGroup()
                .addGroup(pnl_menuTab_HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_tab_dshd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btn_tab_tkhd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnl_FormHoaDon.add(pnl_menuTab_HoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1090, 50));

        pnl_tab_Form_DSHoaDon.setBackground(new java.awt.Color(0, 153, 153));
        pnl_tab_Form_DSHoaDon.add(frmHoaDon1);

        pnl_FormHoaDon.add(pnl_tab_Form_DSHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1090, 620));

        pnl_tab_FormTKHoaDon.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout pnl_tab_FormTKHoaDonLayout = new javax.swing.GroupLayout(pnl_tab_FormTKHoaDon);
        pnl_tab_FormTKHoaDon.setLayout(pnl_tab_FormTKHoaDonLayout);
        pnl_tab_FormTKHoaDonLayout.setHorizontalGroup(
            pnl_tab_FormTKHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
        );
        pnl_tab_FormTKHoaDonLayout.setVerticalGroup(
            pnl_tab_FormTKHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        pnl_FormHoaDon.add(pnl_tab_FormTKHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1090, 620));

        pnl_Main.add(pnl_FormHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 1090, 700));
        pnl_Main.add(frmSanPham2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, -1, -1));
        pnl_Main.add(frmKhachHang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, -1, -1));
        pnl_Main.add(frmBanHang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, -1, -1));
        pnl_Main.add(frmNhanVien1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, -1, -1));
        pnl_Main.add(frmNhaCungCap1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, -1, -1));
        pnl_Main.add(frmHeThong1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, -1, -1));
        pnl_Main.add(frmThongKe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, -1, -1));
        pnl_Main.add(frmThongTinTaiKhoan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_Main, javax.swing.GroupLayout.PREFERRED_SIZE, 1300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_Main, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void KeyShort() {
        //Form BanHang
//        btn_XoaMatHang.setMnemonic(KeyEvent.VK_0);
    }

    public void CustomTable() {
        //Table Khách hàng
//        jTable1.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD, 13));
//        jTable1.getTableHeader().setOpaque(false);
//        jTable1.setRowHeight(25);
        //Table BanhHang
        //heder =  tbl_BanHang.getTableHeader();
//        tbl_BanHang.getTableHeader().setFont(new Font("Consolas",Font.BOLD, 16));
//        tbl_BanHang.getTableHeader().setOpaque(false);
//        tbl_BanHang.getTableHeader().setBackground(Color.red);
//        tbl_BanHang.getTableHeader().setReorderingAllowed(false);

    }

//    public void SetActiveBorder(){
//        //Form he thong
//        btn_tab_HeThong.setBorder(active_border);
//        btn_tab_HeThong.setForeground(Color.black);
//        //Form ban hagn
//        
//        
//    }
    public void Slider() {
        SetImgSize(2);
        tm = new Timer(2000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                SetImgSize(x);
                x += 1;
                if (x >= list.length) {
                    x = 0;
                }

            }
        });
        pnl_ImgTQ.add(lbl_ImgTQ);
        tm.start();
    }

    public void SetImgSize(int i) {
        ImageIcon icon = new ImageIcon(list[i]);
        Image img = icon.getImage();
        Image newImg = img.getScaledInstance(lbl_ImgTQ.getWidth(), pnl_ImgTQ.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon newImc = new ImageIcon(newImg);
        lbl_ImgTQ.setIcon(newImc);
    }


    private void pnl_button_TongQuanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_button_TongQuanMouseClicked
        // TODO add your handling code here:
        pnl_FormTongQuan.setVisible(true);
        frmBanHang1.setVisible(false);
        frmKhachHang1.setVisible(false);
        frmSanPham2.setVisible(false);
        frmNhanVien1.setVisible(false);
        pnl_FormHoaDon.setVisible(false);
        frmHeThong1.setVisible(false);
        frmThongKe1.setVisible(false);
        frmThongTinTaiKhoan1.setVisible(false);
        frmNhaCungCap1.setVisible(false);

        pnl_button_TongQuan.setBackground(Color.white);
        pnl_button_BanHang.setBackground(new Color(153, 204, 255));
        pnl_button_SanPham.setBackground(new Color(153, 204, 255));
        pnl_button_KhachHang.setBackground(new Color(153, 204, 255));
        pnl_button_NhanVien.setBackground(new Color(153, 204, 255));
        pnl_button_HoaDon.setBackground(new Color(153, 204, 255));
        pnl_button_HeThong.setBackground(new Color(153, 204, 255));
        pnl_button_ThongKe.setBackground(new Color(153, 204, 255));
        pnl_button_NhaCungCap.setBackground(new Color(153, 204, 255));
        btn_active_TTTK.setBorder(null);


    }//GEN-LAST:event_pnl_button_TongQuanMouseClicked

    private void pnl_button_BanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_button_BanHangMouseClicked
        // TODO add your handling code here:
        pnl_FormTongQuan.setVisible(false);
        frmBanHang1.setVisible(true);
        frmKhachHang1.setVisible(false);
        frmSanPham2.setVisible(false);
        frmNhanVien1.setVisible(false);
        pnl_FormHoaDon.setVisible(false);
        frmHeThong1.setVisible(false);
        frmThongKe1.setVisible(false);
        frmThongTinTaiKhoan1.setVisible(false);
        frmNhaCungCap1.setVisible(false);

        pnl_button_TongQuan.setBackground(new Color(153, 204, 255));
        pnl_button_BanHang.setBackground(Color.white);
        pnl_button_SanPham.setBackground(new Color(153, 204, 255));
        pnl_button_KhachHang.setBackground(new Color(153, 204, 255));
        pnl_button_NhanVien.setBackground(new Color(153, 204, 255));
        pnl_button_HoaDon.setBackground(new Color(153, 204, 255));
        pnl_button_HeThong.setBackground(new Color(153, 204, 255));
        pnl_button_ThongKe.setBackground(new Color(153, 204, 255));
        pnl_button_NhaCungCap.setBackground(new Color(153, 204, 255));
        btn_active_TTTK.setBorder(null);
    }//GEN-LAST:event_pnl_button_BanHangMouseClicked

    private void pnl_button_SanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_button_SanPhamMouseClicked
        // TODO add your handling code here:
        pnl_FormTongQuan.setVisible(false);
        frmBanHang1.setVisible(false);
        frmKhachHang1.setVisible(false);
        frmSanPham2.setVisible(true);
        frmNhanVien1.setVisible(false);
        pnl_FormHoaDon.setVisible(false);
        frmHeThong1.setVisible(false);
        frmThongKe1.setVisible(false);
        frmThongTinTaiKhoan1.setVisible(false);
        frmNhaCungCap1.setVisible(false);

        pnl_button_TongQuan.setBackground(new Color(153, 204, 255));
        pnl_button_BanHang.setBackground(new Color(153, 204, 255));
        pnl_button_SanPham.setBackground(Color.white);
        pnl_button_KhachHang.setBackground(new Color(153, 204, 255));
        pnl_button_NhanVien.setBackground(new Color(153, 204, 255));
        pnl_button_HoaDon.setBackground(new Color(153, 204, 255));
        pnl_button_HeThong.setBackground(new Color(153, 204, 255));
        pnl_button_ThongKe.setBackground(new Color(153, 204, 255));
        pnl_button_NhaCungCap.setBackground(new Color(153, 204, 255));
        btn_active_TTTK.setBorder(null);
    }//GEN-LAST:event_pnl_button_SanPhamMouseClicked

    private void pnl_button_KhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_button_KhachHangMouseClicked
        // TODO add your handling code here:
        pnl_FormTongQuan.setVisible(false);
        frmBanHang1.setVisible(false);
        frmKhachHang1.setVisible(true);
        frmSanPham2.setVisible(false);
        frmNhanVien1.setVisible(false);
        pnl_FormHoaDon.setVisible(false);
        frmHeThong1.setVisible(false);
        frmThongKe1.setVisible(false);
        frmThongTinTaiKhoan1.setVisible(false);
        frmNhaCungCap1.setVisible(false);

        pnl_button_TongQuan.setBackground(new Color(153, 204, 255));
        pnl_button_BanHang.setBackground(new Color(153, 204, 255));
        pnl_button_SanPham.setBackground(new Color(153, 204, 255));
        pnl_button_KhachHang.setBackground(Color.white);
        pnl_button_NhanVien.setBackground(new Color(153, 204, 255));
        pnl_button_HoaDon.setBackground(new Color(153, 204, 255));
        pnl_button_HeThong.setBackground(new Color(153, 204, 255));
        pnl_button_ThongKe.setBackground(new Color(153, 204, 255));
        pnl_button_NhaCungCap.setBackground(new Color(153, 204, 255));
        btn_active_TTTK.setBorder(null);
    }//GEN-LAST:event_pnl_button_KhachHangMouseClicked

    private void pnl_button_NhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_button_NhanVienMouseClicked
        // TODO add your handling code here:
        pnl_FormTongQuan.setVisible(false);
        frmBanHang1.setVisible(false);
        frmKhachHang1.setVisible(false);
        frmSanPham2.setVisible(false);
        frmNhanVien1.setVisible(true);
        pnl_FormHoaDon.setVisible(false);
        frmHeThong1.setVisible(false);
        frmThongKe1.setVisible(false);
        frmThongTinTaiKhoan1.setVisible(false);
        frmNhaCungCap1.setVisible(false);

        pnl_button_TongQuan.setBackground(new Color(153, 204, 255));
        pnl_button_BanHang.setBackground(new Color(153, 204, 255));
        pnl_button_SanPham.setBackground(new Color(153, 204, 255));
        pnl_button_KhachHang.setBackground(new Color(153, 204, 255));
        pnl_button_NhanVien.setBackground(Color.white);
        pnl_button_HoaDon.setBackground(new Color(153, 204, 255));
        pnl_button_HeThong.setBackground(new Color(153, 204, 255));
        pnl_button_ThongKe.setBackground(new Color(153, 204, 255));
        pnl_button_NhaCungCap.setBackground(new Color(153, 204, 255));
        btn_active_TTTK.setBorder(null);
    }//GEN-LAST:event_pnl_button_NhanVienMouseClicked

    private void pnl_button_HoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_button_HoaDonMouseClicked
        // TODO add your handling code here:
        pnl_FormTongQuan.setVisible(false);
        frmBanHang1.setVisible(false);
        frmKhachHang1.setVisible(false);
        frmSanPham2.setVisible(false);
        frmNhanVien1.setVisible(false);
        pnl_FormHoaDon.setVisible(true);
        frmHeThong1.setVisible(false);
        frmThongKe1.setVisible(false);
        frmThongTinTaiKhoan1.setVisible(false);
        frmNhaCungCap1.setVisible(false);

        pnl_button_TongQuan.setBackground(new Color(153, 204, 255));
        pnl_button_BanHang.setBackground(new Color(153, 204, 255));
        pnl_button_SanPham.setBackground(new Color(153, 204, 255));
        pnl_button_KhachHang.setBackground(new Color(153, 204, 255));
        pnl_button_NhanVien.setBackground(new Color(153, 204, 255));
        pnl_button_HoaDon.setBackground(Color.white);
        pnl_button_HeThong.setBackground(new Color(153, 204, 255));
        pnl_button_ThongKe.setBackground(new Color(153, 204, 255));
        pnl_button_NhaCungCap.setBackground(new Color(153, 204, 255));
        btn_active_TTTK.setBorder(null);
    }//GEN-LAST:event_pnl_button_HoaDonMouseClicked

    private void pnl_button_HeThongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_button_HeThongMouseClicked
        // TODO add your handling code here:
        pnl_FormTongQuan.setVisible(false);
        frmBanHang1.setVisible(false);
        frmKhachHang1.setVisible(false);
        frmSanPham2.setVisible(false);
        frmNhanVien1.setVisible(false);
        pnl_FormHoaDon.setVisible(false);
        frmHeThong1.setVisible(true);
        frmThongKe1.setVisible(false);
        frmThongTinTaiKhoan1.setVisible(false);
        frmNhaCungCap1.setVisible(false);

        pnl_button_TongQuan.setBackground(new Color(153, 204, 255));
        pnl_button_BanHang.setBackground(new Color(153, 204, 255));
        pnl_button_SanPham.setBackground(new Color(153, 204, 255));
        pnl_button_KhachHang.setBackground(new Color(153, 204, 255));
        pnl_button_NhanVien.setBackground(new Color(153, 204, 255));
        pnl_button_HoaDon.setBackground(new Color(153, 204, 255));
        pnl_button_HeThong.setBackground(Color.white);
        pnl_button_ThongKe.setBackground(new Color(153, 204, 255));
        pnl_button_NhaCungCap.setBackground(new Color(153, 204, 255));
        btn_active_TTTK.setBorder(null);
    }//GEN-LAST:event_pnl_button_HeThongMouseClicked

    private void pnl_button_ThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_button_ThongKeMouseClicked
        // TODO add your handling code here:
        pnl_FormTongQuan.setVisible(false);
        frmBanHang1.setVisible(false);
        frmKhachHang1.setVisible(false);
        frmSanPham2.setVisible(false);
        frmNhanVien1.setVisible(false);
        pnl_FormHoaDon.setVisible(false);
        frmHeThong1.setVisible(false);
        frmThongKe1.setVisible(true);
        frmThongTinTaiKhoan1.setVisible(false);
        frmNhaCungCap1.setVisible(false);

        pnl_button_TongQuan.setBackground(new Color(153, 204, 255));
        pnl_button_BanHang.setBackground(new Color(153, 204, 255));
        pnl_button_SanPham.setBackground(new Color(153, 204, 255));
        pnl_button_KhachHang.setBackground(new Color(153, 204, 255));
        pnl_button_NhanVien.setBackground(new Color(153, 204, 255));
        pnl_button_HoaDon.setBackground(new Color(153, 204, 255));
        pnl_button_HeThong.setBackground(new Color(153, 204, 255));
        pnl_button_ThongKe.setBackground(Color.white);
        pnl_button_NhaCungCap.setBackground(new Color(153, 204, 255));
        btn_active_TTTK.setBorder(null);
    }//GEN-LAST:event_pnl_button_ThongKeMouseClicked

    private void btn_tab_dshdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tab_dshdMouseClicked
        // TODO add your handling code here:
        pnl_tab_Form_DSHoaDon.setVisible(true);
        pnl_tab_FormTKHoaDon.setVisible(false);
        // pnl_tab_FormTKSP.setVisible(false);
//        pnl_tab_FormTKNCC.setVisible(false);
    }//GEN-LAST:event_btn_tab_dshdMouseClicked

    private void btn_tab_dshdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tab_dshdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tab_dshdActionPerformed

    private void btn_tab_tkhdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tab_tkhdMouseClicked
        // TODO add your handling code here:
        pnl_tab_Form_DSHoaDon.setVisible(false);
        pnl_tab_FormTKHoaDon.setVisible(true);
        // pnl_tab_FormTKSP.setVisible(false);
//        pnl_tab_FormTKNCC.setVisible(false);
    }//GEN-LAST:event_btn_tab_tkhdMouseClicked

    private void pnl_ThongTinTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_ThongTinTaiKhoanMouseClicked
        // TODO add your handling code here:
        pnl_FormTongQuan.setVisible(false);
        frmBanHang1.setVisible(false);
        frmKhachHang1.setVisible(false);
        frmSanPham2.setVisible(false);
        frmNhanVien1.setVisible(false);
        pnl_FormHoaDon.setVisible(false);
        frmHeThong1.setVisible(false);
        frmThongKe1.setVisible(false);
        frmThongTinTaiKhoan1.setVisible(true);
        frmNhaCungCap1.setVisible(false);
        pnl_button_TongQuan.setBackground(new Color(153, 204, 255));
        pnl_button_BanHang.setBackground(new Color(153, 204, 255));
        pnl_button_SanPham.setBackground(new Color(153, 204, 255));
        pnl_button_KhachHang.setBackground(new Color(153, 204, 255));
        pnl_button_NhanVien.setBackground(new Color(153, 204, 255));
        pnl_button_HoaDon.setBackground(new Color(153, 204, 255));
        pnl_button_HeThong.setBackground(new Color(153, 204, 255));
        pnl_button_ThongKe.setBackground(new Color(153, 204, 255));
        pnl_button_NhaCungCap.setBackground(new Color(153, 204, 255));
        btn_active_TTTK.setBorder(BorderFactory.createMatteBorder(0, 8, 0, 0, new Color(3, 65, 143)));
//        pnl_ThongTinTaiKhoan.setBackground(Color.white);

        //new TitledBorder(new EtchedBorder(EtchedBorder.LOWERED, new Color(255, 255, 255), new Color(160, 160, 160))
    }//GEN-LAST:event_pnl_ThongTinTaiKhoanMouseClicked

    private void pnl_button_NhaCungCapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_button_NhaCungCapMouseClicked
        pnl_FormTongQuan.setVisible(false);
        frmBanHang1.setVisible(false);
        frmKhachHang1.setVisible(false);
        frmSanPham2.setVisible(false);
        frmNhanVien1.setVisible(false);
        pnl_FormHoaDon.setVisible(false);
        frmHeThong1.setVisible(false);
        frmThongKe1.setVisible(false);
        frmThongTinTaiKhoan1.setVisible(false);
        frmNhaCungCap1.setVisible(true);
        pnl_button_TongQuan.setBackground(new Color(153, 204, 255));
        pnl_button_BanHang.setBackground(new Color(153, 204, 255));
        pnl_button_SanPham.setBackground(new Color(153, 204, 255));
        pnl_button_KhachHang.setBackground(new Color(153, 204, 255));
        pnl_button_NhanVien.setBackground(new Color(153, 204, 255));
        pnl_button_HoaDon.setBackground(new Color(153, 204, 255));
        pnl_button_HeThong.setBackground(new Color(153, 204, 255));
        pnl_button_ThongKe.setBackground(new Color(153, 204, 255));
        pnl_button_NhaCungCap.setBackground(Color.white);

        btn_active_TTTK.setBorder(null);
    }//GEN-LAST:event_pnl_button_NhaCungCapMouseClicked

    private void btn_active_TTTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_active_TTTKActionPerformed

    }//GEN-LAST:event_btn_active_TTTKActionPerformed

//    private List<DataSearch> search(String search) {
//        int limitData = 7;
//        List<DataSearch> list = new ArrayList<>();
//        String dataTesting[] = {"Dangdt","Danggodboi","hoang anh","tiendat"};
//        for (String d : dataTesting) {
//            if (d.toLowerCase().contains(search)) {
//                boolean story = isStory(d);
//                if (story) {
//                    list.add(0, new DataSearch(d, story));
//                    //  add or insert to first record
//                } else {
//                    list.add(new DataSearch(d, story));
//                    //  add to last record
//                }
//                if (list.size() == limitData) {
//                    break;
//                }
//            }
//        }
//        return list;
//    }
//    private boolean isStory(String text) {
//        for (String d : dataStory) {
//            if (d.toLowerCase().equals(text.toLowerCase())) {
//                return true;
//            }
//        }
//        return false;
//    }
//    String dataStory[] = {"300 - Rise of an Empire",
//        "Empire Records",
//        "Empire State",
//        "Frozen",
//        "The Courier"};
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GD_Chinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GD_Chinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GD_Chinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GD_Chinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GD_Chinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_active_TTTK;
    private javax.swing.JButton btn_tab_dshd;
    private javax.swing.JButton btn_tab_tkhd;
    private Gui.FrmBanHang frmBanHang1;
    private Gui.FrmHeThong frmHeThong1;
    private Gui.FrmHoaDon frmHoaDon1;
    private Gui.FrmKhachHang frmKhachHang1;
    private Gui.FrmNhaCungCap frmNhaCungCap1;
    private Gui.FrmNhanVien frmNhanVien1;
    private Gui.FrmSanPham frmSanPham2;
    private Gui.FrmThongKe frmThongKe1;
    private Gui.FrmThongTinTaiKhoan frmThongTinTaiKhoan1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_ImgTQ;
    private javax.swing.JLabel lbl_Img_profile1;
    private javax.swing.JLabel lbl_Img_profile4;
    private javax.swing.JLabel lbl_Img_profile5;
    private javax.swing.JLabel lbl_Name_profile1;
    private javax.swing.JLabel lbl_Name_profile4;
    private javax.swing.JLabel lbl_Name_profile5;
    private javax.swing.JLabel lbl_Title_profile1;
    private javax.swing.JLabel lbl_Title_profile4;
    private javax.swing.JLabel lbl_Title_profile5;
    private javax.swing.JLabel lbl_icon_TQ;
    private javax.swing.JLabel lbl_icon_TaiKhoan;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_logo_BanHang;
    private javax.swing.JLabel lbl_logo_HeThong;
    private javax.swing.JLabel lbl_logo_HoaDon;
    private javax.swing.JLabel lbl_logo_KhachHang;
    private javax.swing.JLabel lbl_logo_NCC;
    private javax.swing.JLabel lbl_logo_NhanVien;
    private javax.swing.JLabel lbl_logo_SanPham;
    private javax.swing.JLabel lbl_logo_ThongKe;
    private javax.swing.JLabel lbl_logo_TongQuan;
    private javax.swing.JLabel lbl_text;
    private javax.swing.JLabel lbl_text_HoaDon;
    private javax.swing.JLabel lbl_title_BanHang;
    private javax.swing.JLabel lbl_title_HeThong;
    private javax.swing.JLabel lbl_title_HoaDon;
    private javax.swing.JLabel lbl_title_KhachHang;
    private javax.swing.JLabel lbl_title_NCC;
    private javax.swing.JLabel lbl_title_NhanVien;
    private javax.swing.JLabel lbl_title_SanPham;
    private javax.swing.JLabel lbl_title_TaiKhoan;
    private javax.swing.JLabel lbl_title_TaiKhoan1;
    private javax.swing.JLabel lbl_title_ThongKe;
    private javax.swing.JLabel lbl_title_TongQuan;
    private javax.swing.JPanel pnl_FormHoaDon;
    private javax.swing.JPanel pnl_FormTongQuan;
    private javax.swing.JPanel pnl_ImgTQ;
    private javax.swing.JPanel pnl_Main;
    private javax.swing.JPanel pnl_Menu_button;
    private javax.swing.JPanel pnl_Menu_logo;
    private javax.swing.JPanel pnl_Menu_main;
    private javax.swing.JPanel pnl_ThongTinTaiKhoan;
    private javax.swing.JPanel pnl_button_BanHang;
    private javax.swing.JPanel pnl_button_HeThong;
    private javax.swing.JPanel pnl_button_HoaDon;
    private javax.swing.JPanel pnl_button_KhachHang;
    private javax.swing.JPanel pnl_button_NhaCungCap;
    private javax.swing.JPanel pnl_button_NhanVien;
    private javax.swing.JPanel pnl_button_SanPham;
    private javax.swing.JPanel pnl_button_ThongKe;
    private javax.swing.JPanel pnl_button_TongQuan;
    private javax.swing.JPanel pnl_menuTab_HoaDon;
    private javax.swing.JPanel pnl_profile1;
    private javax.swing.JPanel pnl_profile4;
    private javax.swing.JPanel pnl_profile5;
    private javax.swing.JPanel pnl_tab_FormTKHoaDon;
    private javax.swing.JPanel pnl_tab_Form_DSHoaDon;
    // End of variables declaration//GEN-END:variables
}
